test1

diff --git a/.github/workflows/be-dev-cd.yml b/.github/workflows/be-dev-cd.yml
--- a/.github/workflows/be-dev-cd.yml
+++ b/.github/workflows/be-dev-cd.yml
@@ -2,42 +2,31 @@ name: BE Dev CD
 
 on:
   push:
-    branches: [ "develop" ]
+    branches: [ "test-deploy" ]
 
 jobs:
   deploy:
-    if: |
-      github.actor == 'yesjuhee' || 
-      github.actor == 'Minuring' ||
-      github.actor == 'eueo8259' ||
-      github.actor == 'minjae8563'
-    name: Deploy to EC2
     runs-on: self-hosted
-
-    defaults:
-      run:
-        working-directory: ./backend
-
     steps:
       - name: change permission
         run: |
           sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/2025-moaon
-    
-      - name: Checkout repository
-        uses: actions/checkout@v4
+          
+      # - name: Checkout repository
+      #   uses: actions/checkout@v4
 
-      - name: Create .env file from Secrets
+      - name: Check seed data changes
         run: |
-          echo "Creating .env file from GitHub Secrets"
-          cat <<EOF > .env
-          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
-          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
-          SPRING_DATASOURCE_URL_DEV=${{ secrets.SPRING_DATASOURCE_URL_DEV }}
-          SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
-          SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
-          EOF
+          if git diff --quiet origin/test-deploy HEAD -- db/mysql/init; then
+            echo "SEED_CHANGED=false" >> $GITHUB_ENV
+            echo "No changes in seed data detected. Failing the workflow intentionally."
+            exit 1  # 변경 없으면 실패
+          else
+            echo "SEED_CHANGED=true" >> $GITHUB_ENV
+          fi
 
-      - name: Run Docker Compose
+      - name: Restart DB only if seed changed
+        if: env.SEED_CHANGED == 'true'
         run: |
-          sudo docker compose down --rmi all
-          sudo docker compose up --build -d
+          docker-compose down -v
+          docker-compose up -d --build
